image: Visual Studio 2017
configuration:
  - Debug
  - Release
platform:
  - x86
  - x64
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
build:
  project: MissionScanner.sln
