image: Visual Studio 2017
configuration:
  - Debug
  - Release
platform:
  - x86
  - x64
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
build:
  project: MissionScanner.sln
after_build:
  - set PackageBaseName="%APPVEYOR_PROJECT_NAME%-Build%APPVEYOR_BUILD_VERSION%-%CONFIGURATION%"
  - 7z a "%PackageBaseName%.zip" "%APPVEYOR_BUILD_FOLDER%\%PLATFORM%\%CONFIGURATION%\*.exe"
  - 7z a "%PackageBaseName%-DebugSymbolPdb.zip" "%APPVEYOR_BUILD_FOLDER%\%PLATFORM%\%CONFIGURATION%\*.pdb"
artifacts:
  - path: "*.zip"
    name: BuildArtifacts